[project]
name = 'DataChainAfrica'
authors = []
description = 'Blockchain-based mobile data tracking for Africa'
telemetry = false
requirements = []

[contracts.billing]
path = 'contracts/billing.clar'
clarity_version = 4
epoch = 'latest'

[contracts.data-tracking]
path = 'contracts/data-tracking.clar'
clarity_version = 4
epoch = 'latest'

[contracts.data-traits]
path = 'contracts/data-traits.clar'
clarity_version = 4
epoch = 'latest'

[contracts.marketplace]
path = 'contracts/marketplace.clar'
clarity_version = 4
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
